name: Salesforce CI/CD Pipeline
'on':
  pull_request:
    branches:
      - main
  push:
    branches:
      - develop
      - main
jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli # Installs the Salesforce CLI globally using npm
      - name: Authorize Salesforce Org
        run: >-
      - name: Authenticate to Salesforce (JWT)
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          cat server.key
          sf org login jwt --client-id ${{ secrets.SF_CONSUMER_KEY }} --jwt-key-file server.key --username ${{ secrets.SF_USERNAME }} --instance-url ${{ secrets.SF_SERVER_URL }} --alias dbmlightning-dev-ed.my.salesforce.com --set-default
      - name: Validate Deployment
        run: >-
          sf force:source:deploy -p force-app/main/default -c -u dbmlightning-dev-ed.my.salesforce.com
  deploy-to-production:
    needs: validate-deployment
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli
      - name: Authorize Salesforce Org
        run: >-
          sf org login jwt --client-id ${{ secrets.SF_CONSUMER_KEY }} --jwt-key-file server.key --username ${{ secrets.SF_USERNAME }} --instance-url ${{ secrets.SF_SERVER_URL }} --alias dbmlightning-dev-ed.my.salesforce.com --set-default-dev-hub
      - name: Deploy to Production
        run: >-
          sf force:source:deploy -p force-app/main/default -u
          dbmlightning-dev-ed.my.salesforce.com
