name: Salesforce CI/CD Pipeline
'on':
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli
      - name: Authenticate to Salesforce (JWT)
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" >./server.key
          sf org login jwt --client-id ${{ secrets.SF_CONSUMER_KEY }} --jwt-key-file ./server.key --username ${{ secrets.SF_USERNAME }} --instance-url ${{ secrets.SF_SERVER_URL }} --alias dbmlightning-dev-ed.my.salesforce.com --set-default
          rm ./server.key
      - name: Validate Deployment
        run: sf project deploy validate --source-dir {{ vars.SF_SOURCE_DIR }} --target-org ${{ vars.SF_ORG_ALIAS }} --wait ${{ vars.SF_WAIT_TIME }} --test-level RunSpecifiedTests --tests "SYS_UTILS_TEST"
  deploy-to-production:
    needs: validate-deployment
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli
      - name: Authenticate to Salesforce (JWT)
        run: sf org login jwt --client-id ${{ secrets.SF_CONSUMER_KEY }} --jwt-key-file server.key --username ${{ secrets.SF_USERNAME }} --instance-url ${{ secrets.SF_SERVER_URL }} --alias dbmlightning-dev-ed.my.salesforce.com --set-default-dev-hub
      - name: Deploy to Production
        run: sf project deploy start --source-dir ${{ vars.SF_SOURCE_DIR }} --target-org ${{ vars.SF_ORG_ALIAS }} --wait ${{ vars.SF_WAIT_TIME }}
